[package]
name = "mupdf"
version = "0.0.3"
authors = ["messense <messense@icloud.com>"]
edition = "2018"
description = "Safe Rust wrapper to MuPDF"
keywords = ["pdf", "mupdf"]
license = "GPL-3.0"
readme = "README.md"
repository = "https://github.com/messense/mupdf-rs"

[features]
default = ["noto-small", "no-cjk", "js", "xps", "svg", "cbz", "img", "html", "epub"]
sys-lib = ["mupdf-sys/sys-lib"]
x11 = ["mupdf-sys/x11"]
opengl = ["mupdf-sys/opengl"]
curl = ["mupdf-sys/curl"]
noto-small = ["mupdf-sys/noto-small"]
no-cjk = ["mupdf-sys/no-cjk"]
tofu = ["mupdf-sys/tofu"]
js = ["mupdf-sys/js"]
xps = ["mupdf-sys/xps"]
svg = ["mupdf-sys/svg"]
cbz = ["mupdf-sys/cbz"]
img = ["mupdf-sys/img"]
html = ["mupdf-sys/html"]
epub = ["mupdf-sys/epub"]

[dependencies]
mupdf-sys = { version = "0.0.3", path = "mupdf-sys" }
once_cell = "1.3.1"
num_enum = "0.5.1"
bitflags = "1.2.1"

[workspace]
members = [
    ".",
    "mupdf-sys"
]

[dev-dependencies]
crossbeam-utils = "0.7.2"
